export const customStyles = {
  content: {
    top: "45%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    padding: 0,
    border: "none",
    "box-shadow": "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    width: "50%",
    borderRadius: "12px",
    minWidth: "900px",
  },
};

export const pModalStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    padding: 0,
    border: "none",
    "box-shadow": "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    width: "500px",
    opacity: 1,
    borderRadius: "12px",
  },
};

export const sampleUserData = [
  {
    firstName: "Alvin",
    lastName: "Acosta",
    email: "aa@gmail.com",
    number: "09164209977",
    address: "21 Falcon St.",
    municipality: "Quezon City",
    region: "NCR",
    birthday: "6/16/87",
  },
  {
    firstName: "Alvin",
    lastName: "Acosta",
    email: "aa@gmail.com",
    number: "09164209977",
    address: "21 Falcon St.",
    municipality: "Quezon City",
    region: "NCR",
    birthday: "6/16/87",
  },
  {
    firstName: "Alvin",
    lastName: "Acosta",
    email: "aa@gmail.com",
    number: "09164209977",
    address: "21 Falcon St.",
    municipality: "Quezon City",
    region: "NCR",
    birthday: "6/16/87",
  },
  {
    firstName: "Alvin",
    lastName: "Acosta",
    email: "aa@gmail.com",
    number: "09164209977",
    address: "21 Falcon St.",
    municipality: "Quezon City",
    region: "NCR",
    birthday: "6/16/87",
  },
  {
    firstName: "Alvin",
    lastName: "Acosta",
    email: "aa@gmail.com",
    number: "09164209977",
    address: "21 Falcon St.",
    municipality: "Quezon City",
    region: "NCR",
    birthday: "6/16/87",
  },
];
