export const announcementModalStyles = {
  content: {
    top: "45%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    padding: 0,
    border: "none",
    "box-shadow": "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    width: "500px",
    borderRadius: "12px",
    // minWidth: "900px",
  },
};

export const viewAnnouncementModalStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
    padding: 0,
    border: "none",
    "box-shadow": "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    width: "500px",
    opacity: 1,
    borderRadius: "12px",
  },
};

export const sampleUserData = [
  {
    title: "BBM Vs Corruption",
    description: "Lorem impsum dolor sit amet, conectetur adi elit.",
    category: "Nationwide",
  },
  {
    title: "Campaign para sa mahihirap",
    description: "Lorem impsum dolor sit amet, conectetur adi elit.",
    category: "Nationwide",
  },
  {
    title: "Libreng Bakuna para sa lahat",
    description: "Lorem impsum dolor sit amet, conectetur adi elit.",
    category: "Regional",
  },
  {
    title: "Covid tutuldukan na!",
    description: "Lorem impsum dolor sit amet, conectetur adi elit.",
    category: "Regional",
  },
  {
    title: "Ayuda maibigay sa nararapat",
    description: "Lorem impsum dolor sit amet, conectetur adi elit.",
    category: "Nationwide",
  },
];

export const sampleRegionData = [
  {
    region: "NCR",
    municipalities: [
      "Manila",
      "Mandaluyong",
      "Marikina",
      "Pasig",
      "Quezon City",
      "San Juan",
      "Caloocan",
      "Malabon",
      "Navotas",
      "Valenzuela",
      "Las Pinas",
      "Makati",
      "Muntinlupa",
      "Paranaque",
      "Pasay",
      "Pateros",
      "Taguig",
    ],
  },
  {
    region: "CAT",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region I",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region II",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region III",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region IV",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region V",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region VI",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region VII",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region VIII",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region IX",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region X",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region XI",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region XII",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "Region XII",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    region: "BARMN",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoan",
      "Gimoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
];
